### ISSUE TITLE
is python2.7 required ?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [Valdes-Tresanco-MS/AMDock#10]
hi again,

AMDock/AMDock.sh contains:
```
PYMOL_PATH=${PYMOL_PATH:=`python2.7 -c "from imp import find_module; print find_module('pymol')[1]"`}
```
Is the python2.7 version for pymol required? or only the python used to build pymol is needed here?

I have also replaced the PYMOL_* with:
```
PYMOL_DATA=${PYMOL_PATH}/pymol_path/data
PYMOL_SCRIPTS=${PYMOL_PATH}/pymol_path/scripts
CHEMPY_DATA=${PYMOL_PATH}/pymol_path/data/chempy
```
as we don't have pymol installed in /usr

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, yes in both cases.
Since the transition between Python2 and Python3 takes considerable work, we also decided to implement new features. This has delayed the release of version 2 a bit, which solves most of the problems and limitations of AMDock. Also, due to my PhD commitments, I have not had enough time to finish it. The current state of v2.0 is advanced so I think we can launch it in the next few months. We will make an effort!
Best!
Mario S.
