### ISSUE TITLE
don't use sudo with your script without warning

### ISSUE THREAD

**Issue by truatpasteurdotfr** [Valdes-Tresanco-MS/AMDock#9]
Please, as a courtesy to your users, do not hide the sudo commands in your install.sh script.

If needed ask them to re-run ./install.sh with sudo.

**Comment by Valdes-Tresanco-MS** [comment]
Thanks @truatpasteurdotfr 

We try to be as transparent as possible. Since AMDock was our first software, it may have some problems of this kind. According to the vulnerability analysis, AMDock does not present any, however, I will try to modify install.sh or be more explicit in the documentation.

The installation of AMDock requires access to the system's Python modules folder as this folder requires administrator write rights. We could modify it to install in an external folder that does not require the sudo command, but it would increase the risk of conflicts in PYTHONPATH variable

The new version of AMDock is modular, so this will not be required.
Thank you very much for the suggestions, we will certainly take them into account

Best!
Mario S.

**Comment by truatpasteurdotfr** [comment]
We have quite a lot of python, pymol installed side by side and unless it is your own laptop/development machines, users are seldom allowed to "sudo". If you have users using conda, they already own the python libraries and don't need sudo for installing additionnal librairies. Furthermore, running sudo without being authorised, is usally ringing an alarm for the sysadmin.
Just my 2 cents.

Best regards
